### ISSUE TITLE
debug mode

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#136] opened 2017-09-15 22:52 UTC
Как включить debug mode?

![image](https://user-images.githubusercontent.com/29465298/30506090-b2dc9ce2-9a81-11e7-835a-9b9edbace4e9.png)

**Comment by Levak** [comment] 2017-09-15 23:00
Under a POSIX shell: `make clean debug-wb`.
If you are under Windows, you need to compile the project, using either Cygwin or Mingw.

**Comment by franchesko1437** [comment] 2017-09-16 11:48
What exactly should I compile? you can write more about this

**Comment by Levak** [comment] 2017-09-17 10:57
Duplicate of #123

**Closed by Levak** 2017-09-17 10:57 UTC
Labels: duplicate, question

**Comment by franchesko1437** [comment] 2017-09-17 11:35
in # 123 there is no working version. not written how to do debug mode. Could you send a working folder with a debug mod?

**Comment by Levak** [comment] 2017-09-17 11:39
> Could you send a working folder with a debug mod?

As written in #123 and here, you need to recompile **yourself** warfacebot in debug mode. I gave the command above, it is **your** job to make it work. I do not give support regarding compilation unless there is a bug. Everyone uses the environment they want to (Cygwin, Mingw, GNU/Linux, lxwin), and I am not here to give support to every single one of them.

I assume you have a good reason to work in debug mode, and this reason implies you know how to compile the bot yourself. Otherwise, there is no reason to have the "fancy colors and queries" showing, it is unproductive for a casual use of warfacebot. Debug mode is only needed in face of helping with the development of warfacebot or testing a server implmentation. In both cases, it means you are familiar with compiling code and using your PC.

**Comment by franchesko1437** [comment] 2017-09-17 11:49
Thanks, I'll think about the compilation
