### ISSUE TITLE
cmd close

### ISSUE THREAD

**Issue by KoLLapS1337** [Levak/warfacebot#342] opened 2019-07-20 07:43 UTC
hello, it's me again. i'm back and updated crypt keys, but problem(cmd closes immediately) still exists. what to do?

**Comment by franchesko1437** [comment] 2019-07-20 07:50
Not properly updated.
Duplicate of #99

**Comment by KoLLapS1337** [comment] 2019-07-20 08:59
i just reinstalled wftbot, crypt keys is newest

**Comment by franchesko1437** [comment] 2019-07-20 09:13
[https://github.com/Levak/warfacebot/releases/tag/1.0.15b](url)
I can not reproduce your problem.
My bot is loaded by the link above and it works

**Comment by KoLLapS1337** [comment] 2019-07-20 09:23
ru alpha

**Comment by KoLLapS1337** [comment] 2019-07-20 09:46
installed your version - did not help

**Comment by franchesko1437** [comment] 2019-07-20 10:28
> установил вашу версию - не помогло
У меня все работает, разбирайся.

**Closed** 2019-09-14 13:01 UTC
