### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by bugtesterft** [Levak/warfacebot#383] opened 2019-12-11 20:39 UTC
I usually use the program and update it whenever necessary, in this update I get an error when I try to log in to NA I get the "Authentication failed" message even if the data is correct.
![image](https://user-images.githubusercontent.com/58790658/70658609-f058b580-1c23-11ea-9541-09c15d770409.png)

**Comment by Levak** [comment] 2019-12-11 20:43
Duplicate of #380

**Closed by Levak** 2019-12-11 20:43 UTC
