### ISSUE TITLE
launch bot

### ISSUE THREAD

**Issue by Rustamom** [Levak/warfacebot#394] opened 2019-12-31 14:08 UTC
Updated cfg, but the bot does not work. ru-alpha

![image](https://user-images.githubusercontent.com/48911064/71623822-26b89d80-2bf0-11ea-8458-d2d56634efd7.png)

**Comment by Levak** [comment] 2019-12-31 17:36
Duplicate of #393

**Closed by Levak** 2019-12-31 17:36 UTC

**Comment by Carlsberg34** [comment] 2019-12-31 17:41
some problem
