### ISSUE TITLE
quickplay battle royale 

### ISSUE THREAD

**Issue by Alanx122** [Levak/warfacebot#326] opened 2019-06-07 04:23 UTC
Why can not I get the bot to find the pripyat battle royale? when I put quickplay open lms_pripyat says that the map / mission does not exist I put quickplay open ptb_D17 in that the bot enters some channel pvp in that I put the quickplay start lms_pripyat says that it was not possible to open game room fast (Invalid or expired mission)
![dYjMVRl](https://user-images.githubusercontent.com/46060312/59081097-c617eb00-88c2-11e9-81b2-f933c6fc947c.png)

**Comment by franchesko1437** [comment] 2019-06-07 05:35
инвалид

**Comment by Levak** [comment] 2019-07-02 08:33
Duplicate of #334

**Closed by Levak** 2019-07-02 08:33 UTC
Labels: duplicate
