### ISSUE TITLE
Nao consigo iniciar a partida royale pripyat/mojave com os códigos citados

### ISSUE THREAD

**Issue by eddybanca** [Levak/warfacebot#335] opened 2019-07-01 23:10 UTC

**Comment by eddybanca** [comment] 2019-07-01 23:14
the commands to start the battle royale pripyat / mojave do not work, could you tell which ones are or if they even exist?

**Comment by eddybanca** [comment] 2019-07-02 00:04
CMD# quickplay start lms_pripyat
CMD#      Failed to open quickplay room (Invalid or expired mission)
CMD#

**Comment by Levak** [comment] 2019-07-02 08:25
Duplicate of #334

**Closed by Levak** 2019-07-02 08:25 UTC
Labels: duplicate
