### ISSUE TITLE
Hello, I need a help please.

### ISSUE THREAD

**Issue by onedayalllwilldie** [Levak/warfacebot#386] opened 2019-12-12 23:36 UTC
Hello, I am new here so I have a problem with launcher I can't log in bot accounts such as pop op message Authentication failed. Can someone help me please thank you! I am using In Na server accounts and all of them checked on the website so I put right all information.

**Comment by Levak** [comment] 2019-12-13 06:33
Duplicate of #380

**Closed by Levak** 2019-12-13 06:33 UTC
