### ISSUE TITLE
"Authentication failed" after update v1.22600.2135.17100

### ISSUE THREAD

**Issue by tetteykn** [Levak/warfacebot#546] opened 2020-09-25 12:10 UTC
Hello Levak, when i try log in with the bot, at the CMD i get Authentication failed

**Comment by tetteykn** [comment] 2020-09-25 12:20
![Screenshot_2](https://user-images.githubusercontent.com/51218189/94266261-cca3f900-ff31-11ea-8219-47884f93d35a.png)

**Comment by ProIsmo** [comment] 2020-09-25 14:51
@tetteykn the authentication failure occurs in the **<auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='WARFACE'></auth>**


b"\x00" + token+ "{:B:}" + randomtextno_clue_what_it_is + b"\x00" + account_id

**Comment by bakedbeans3** [comment] 2020-09-25 15:01
Its because we dont have the updated server keys.  Levak updated the cfg files for the RU servers only.  Question, where and how to obtain those keys?

**Comment by Kavan72** [comment] 2020-09-25 15:19
@bakedbeans3 it's already updated. For keys you need 200iq. Thank you

**Comment by bakedbeans3** [comment] 2020-09-25 16:26
Yo Levak, i know that my.com is going a different direction with bots than before, and that you had answered the forums without your personal opinion.  My opinion is that we are grateful for your contribution in this area, and since the bots only have a 1 second life before being culled by MRAC, they can really only be used for starting games.  I for one want to see that option continue, rather than start up 4 other pcs to load the actual accounts to do the very same thing.  Please, please continue this work.  We need those updated cfg files for all servers.  thanks.

**Comment by bakedbeans3** [comment] 2020-09-25 16:33
Ok i guess im blind i dont see the updated cfg file in the list.  Yep dont have 200 iq.

**Comment by AleksTeam** [comment] 2020-09-26 17:48
They just rewrote the authorization.

**Comment by SencerSofuoglu** [comment] 2020-09-27 06:29
![A F](https://user-images.githubusercontent.com/58823844/94357699-c6358e80-00a3-11eb-9efd-71da73c24c41.jpg)
Hi , i have same problem .. 
Pls help us...

**Comment by west-28** [comment] 2020-09-27 07:34
> They just rewrote the authorization.

Есть возможность поправить бота?

**Comment by SencerSofuoglu** [comment] 2020-09-30 14:58
Working ...

**Comment by Sofuzade** [comment] 2020-12-02 18:03
i dont understand bot  isnt work but levak updating all time .. İf not work why updating ? İf it work why dont you interest our writing?

**Comment by SencerSofuoglu** [comment] 2020-12-02 18:11
"auth. failed closed dispatch.. ."   same like me

**Comment by Levak** [comment] 2020-12-02 18:14
Duplicate of #547

**Closed by Levak** 2020-12-02 18:14 UTC
Labels: EU/NA, RU, duplicate, wontfix
