### ISSUE TITLE
Help RUWF

### ISSUE THREAD

**Issue by SWITCH3ED** [Levak/warfacebot#52] opened 2017-01-23 18:07 UTC
![1](https://cloud.githubusercontent.com/assets/25305127/22216373/e160b624-e1af-11e6-9f51-13a6fa6e6ea5.JPG)

**Comment by Levak** [comment] 2017-01-23 18:22
Duplicate of #20

**Closed by Levak** 2017-01-23 18:22 UTC
Labels: duplicate

**Comment by alexalok** [comment] 2017-01-24 17:10
You can use a wrapper for warfacebot https://mechcraft.ru/mechcraft-бот-standalone/
It is paid, however.

**Comment by SWITCH3ED** [comment] 2017-01-25 15:50
Thanks, programm not free?

**Comment by Levak** [comment] 2017-01-25 18:52
> You can use a wrapper for warfacebot https://mechcraft.ru/mechcraft-бот-standalone/
It is paid, however.

Is Warfacebot AGPLv3 license file shipped with the executable that is installed on the client?

**Comment by alexalok** [comment] 2017-01-25 21:12
yup
