### ISSUE TITLE
Upgrade randombox algorithm

### ISSUE THREAD

**Issue by ptaking** [Levak/warfacebot#73] opened 2017-04-06 02:09 UTC
When we buy 5 randombox in a row, the price will be (example) `6K + 5K + 4K + 3K + 2K = 20K`
But in WFBot, look like it will send "Buy 1 randombox" 5 times. So the price will be `6K + 6K + 6K + 6K + 6K = 30K`.

**Comment by Levak** [comment] 2017-04-17 18:03
Hi,

Sorry for the late answer, completely forgot to.
At the moment, warfacebot is aware of all shop offers and random boxes "variants" (the one you quote). Random box algorithm on warfacebot is even smarter than the official game in the following scenario:

 - Buy 1 box
 - Buy 4 box

On official game client, it will charge you more than on warfacebot, because warfacebot keeps track of the "cycling logic", while official game client will always starts from 0 after pressing the "open" button.

If, on warfacebot, you do `randombox arx 5` it will be equivalent to game client purchases, same as if you did 5 times in a row `randombox arx 1`.

This being put, you mention that you observed higher expanses, which could come from a bug in the cycling logic. If you are able to recompile warfacebot in debug mode `make clean debug-wb` I will be interested in the query that is sent from warfacebot on buying 5 boxes. The IDs should be different each time.

I was not able to reproduce your bug on wfd-boxes.

**Closed** 2017-05-03 15:01 UTC
