### ISSUE TITLE
Levak HELP

### ISSUE THREAD

**Issue by west-28** [Levak/warfacebot#551] opened 2020-09-30 18:53 UTC
Hello Levak, I understand that the support ended on September 20th! I very much ask you to lastly help me fix the authorization, the keys are updated only to no use, since the error "Authentication failed"

Thank you very much for your help !!!

**Comment by I-LOVE-C2H5OH** [comment] 2020-10-01 19:33
what about you? he's tired of this whole project

**Comment by west-28** [comment] 2020-10-02 11:30
> what about you? he's tired of this whole project


if i could fix it myself i would ask here for help me ?!

**Comment by I-LOVE-C2H5OH** [comment] 2020-10-02 12:07
alternatively, you can learn C and fix it yourself

**Comment by Sofuzade** [comment] 2020-12-02 18:05
i dont understand bot isnt work but levak updating all time .. İf not work why updating ? İf it work why dont you interest our writing?

**Comment by SencerSofuoglu** [comment] 2020-12-02 18:08
i dont understand too... Bot not working..

**Comment by Levak** [comment] 2020-12-02 18:14
Duplicate of #547

**Closed by Levak** 2020-12-02 18:14 UTC
Labels: EU/NA, RU, duplicate, wontfix
